import { createTypes } from 'reduxsauce';

export default createTypes(`
	ADD_TODO
	DELETE_TODO
	EDIT_TODO
	FACEBOOK_LOGIN
	GET_CURRENT_USER
	GET_SELECTED_DAY_TODOS
	GOOGLE_LOGIN
	LOGIN_USER
	LOGOUT_USER
	ON_CHANGE_TODOS
	RESET_SELECT_DAY
	SET_CURRENT_USER
	SELECT_DAY
	SELECTED_DAY_TODOS
	TOGGLE_CHECKBOX
`)
